ophyd.AD_Eiger:
  - name: eiger4M
    prefix: "8id:Eiger4M:"
    labels: ["detector", "area_detector"]

ophyd.AD_Lambda:
  - name: lambda2M
    prefix: "8id:Lambda2M:"
    labels: ["detector", "area_detector"]

ophyd.AD_Rigaku:
  - name: rigaku3M
    prefix: "8id:Rigaku3M:"
    labels: ["detector", "area_detector"]

ophyd.AerotechMotor:
  - name: aerotech_stage_x
    prefix: "8id:aeroX:"
    labels: ["motor", "stage"]
  - name: aerotech_stage_y
    prefix: "8id:aeroY:"
    labels: ["motor", "stage"]

ophyd.EpicsMotor:
  - name: huber_theta
    prefix: "8id:Huber:theta"
    labels: ["motor", "diffractometer"]
  - name: slit_top
    prefix: "8id:Slit:top"
    labels: ["motor", "slits"]

ophyd.FastShutter:
  - name: fast_shutter
    prefix: "8id:FastShutter:"
    labels: ["shutter"]

ophyd.XBPM:
  - name: xbpm2
    prefix: "8id:XBPM2:"
    labels: ["diagnostics", "xbpm"]

ophyd.TetrammPico:
  - name: tetramm
    prefix: "8id:Tetramm:"
    labels: ["diagnostics", "picoammeter"]

ophyd.Transfocator:
  - name: transfocator8idd
    prefix: "8idd:Transfocator:"
    labels: ["optics", "transfocator"]
