# hint: pre-commit run --all-files

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # exclude_types: [jupyter]
      - id: check-yaml
      - id: check-toml
      - id: check-ast
        exclude: ^src/instrument/
      # - id: check-docstring-first  # let variables have docstrings
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: mixed-line-ending
        exclude: ^src/instrument/
      - id: end-of-file-fixer
        exclude: ^src/instrument/
      - id: trailing-whitespace
        exclude: ^src/instrument/
      - id: check-case-conflict
      # - id: check-json
      # - id: check-symlinks
      - id: check-executables-have-shebangs
        exclude: ^src/instrument/
  # Don't strip output from jupyter notebooks ATM.
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.7.1
  #   hooks:
  #     - id: nbstripout
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.8
    hooks:
      - id: ruff # replaces Flake8, isort, pydocstyle, pyupgrade
        args:
          - --fix
        exclude: ^src/instrument/
      - id: ruff-format # replaces Black
        exclude: ^src/instrument/
