name: bs_v1

# create:
#   conda env create --force -n bs_v1 -f ./environment.yml --solver=libmamba
co
channels:
  - apsu
  - conda-forge
  - aps-anl-tag
  - defaults

dependencies:
  - aps-dm-api >=5   # linux-64  osx-64


  - pip:
    - apsbss  # only works on APS subnet
