# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

ophyd.EpicsMotor:
- {name: fl2, prefix: 8ideSoft:CR8-E2:m7, labels: ["motor"]}
- {name: fl3, prefix: 8idiSoft:CR8-I2:m7, labels: ["motor"]}
- {name: flag4, prefix: 8iddSoft:CR8-D1:m1, labels: ["motor"]}

xpcs.devices.bd_5a.BD5A:
- name: bd5a
  prefix: "8iddSoft:CR8-D1:US"
  h_base_motor: m9
  v_base_motor: m10

xpcs.devices.damm.Damm:
- name: damm
  prefix: "8iddSoft:CR8-D1:US"
  x_motor: m2
  y_motor: m3

xpcs.devices.fast_shutter.FastShutter:
- name: shutter_8ide
  prefix: "8ideSoft:fastshutter:"

xpcs.devices.filters_8id.Filter2Device:
- name: filter_8ide
  prefix: "8idPyFilter:FL2:"
- name: filter_8idi
  prefix: "8idPyFilter:FL3:"

xpcs.devices.granite.granite_device:
- name: granite
  prefix: "8idiSoft:CR8-I2:US"
  x_motor: m8

xpcs.devices.granite_enable.Valve_Enable:
- name: granite_8idi_valve
  prefix: "8idiSoft:CR8-I2:"

xpcs.devices.hhl_mirrors.HHL_Mirror1:
- name: mr1
  prefix: "8idaSoft:"
xpcs.devices.hhl_mirrors.HHL_Mirror2:
- name: mr2
  prefix: "8idaSoft:"

xpcs.devices.hhl_slits.HHLSlits:
- name: wb_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-1:US"
  pitch_motor: "m3"
  yaw_motor: "m4"
  horizontal_motor: "m1"
  diagonal_motor: "m2"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

- name: mono_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-2:US"
  pitch_motor: "m11"
  yaw_motor: "m12"
  horizontal_motor: "m9"
  diagonal_motor: "m10"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

xpcs.devices.idt_mono.IDTMono:
- name: "idt_mono"
  prefix: "8idaSoft:MONO:US"
  bragg_motor: "m1"
  xtal_gap_motor: "m2"
  flag_motor: "m3"
  coarse_pitch_motor: "m5"
  coarse_roll_motor: "m6"
  x_pitch_motor: "m7"
  y_pitch_motor: "m8"

xpcs.devices.labjack_support.LabJack:
- name: "labjack"
  prefix: "8idiSoft:LJT705:"

xpcs.devices.qnw_device.QnwDevice:
- name: qnw_env1
  prefix: "8idiSoft:QNWenv_1:"
  readback_pv: null
- name: qnw_env2
  prefix: "8idiSoft:QNWenv_2:"
  readback_pv: null
- name: qnw_env3
  prefix: "8idiSoft:QNWenv_3:"
  readback_pv: null

xpcs.devices.registers_device.EpicsPvStorageRegisters:
- name: pv_registers
  prefix: "8idiSoft:"

xpcs.devices.slit_base.SlitBase:
- name: sl4_base
  prefix: "8iddSoft:CR8-D1:US"
  h_motor: m15
  v_motor: m16
- name: sl5_base
  prefix: 8ideSoft:CR8-E2:US
  h_motor: m5
  v_motor: m6
- name: sl7_base
  prefix: "8ideSoft:CR8-E2:US"
  h_motor: m15
  v_motor: m16
- name: sl8_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m5
  v_motor: m6
- name: sl9_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m15
  v_motor: m16


# apstools.devices.area_detector_factory.ad_creator:

# - name: eiger4M
#   prefix: "8idEiger4M:"
#   # IOC host: beryl
#   # IOC top: /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idEiger4m/iocBoot/ioc8idEiger4m/softioc/8idEiger4m.pl
#   labels:
#   - area_detector
#   - detector
#   - detectors
#   plugins:
#   - badpix1 # apstools 1.7.3+
#   - cam:
#       class: 8id.devices.ad_common.EigerDetectorCam_V34
#   - image
#   - hdf1:
#       class: apstools.devices.area_detector_support.AD_EpicsFileNameHDF5Plugin
#       # TODO #41 switch to the Voyager-based path structure: "/gdata/..."
#       read_path_template: /home/8ididata/2023-2/pvaccess_test/
#       # same filesystem for IOC & Bluesky
#       write_path_template: /home/8ididata/2023-2/pvaccess_test/
#   - overlay1
#   - pva
#   - roi1
#   - stats1

# 8id.devices.AD_Lambda:
# - name: lambda2M
#   prefix: "8id:Lambda2M:"
#   labels: [ "detector", "area_detector" ]

# 8id.devices.AD_Rigaku:
# - name: rigaku3M
#   prefix: "8id:Rigaku3M:"
#   labels: [ "detector", "area_detector" ]

# 8id.devices.AerotechMotor:
# - name: aerotech_stage_x
#   prefix: "8id:aeroX:"
#   labels: [ "motor", "stage" ]
# - name: aerotech_stage_y
#   prefix: "8id:aeroY:"
#   labels: [ "motor", "stage" ]

# 8id.devices.EpicsMotor:
# - name: huber_theta
#   prefix: "8id:Huber:theta"
#   labels: [ "motor", "diffractometer" ]
# - name: slit_top
#   prefix: "8id:Slit:top"
#   labels: [ "motor", "slits" ]

# 8id.devices.FastShutter:
# - name: fast_shutter
#   prefix: "8id:FastShutter:"
#   labels: [ "shutter" ]

# 8id.devices.XBPM:
# - name: xbpm2
#   prefix: "8id:XBPM2:"
#   labels: [ "diagnostics", "xbpm" ]

# 8id.devices.TetrammPico:
# - name: tetramm
#   prefix: "8id:Tetramm:"
#   labels: [ "diagnostics", "picoammeter" ]

# 8id.devices.Transfocator:
# - name: transfocator8idd
#   prefix: "8idd:Transfocator:"
#   labels: [ "optics", "transfocator" ]

###############################

## THIS ARE EXAMPLES OF OTHER DEVICES THAT YOU CAN USE
# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
