# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

ophyd.EpicsMotor:
- {name: fl2, prefix: 8ideSoft:CR8-E2:m7, labels: ["motor"]}
- {name: fl3, prefix: 8idiSoft:CR8-I2:m7, labels: ["motor"]}
- {name: flag4, prefix: 8iddSoft:CR8-D1:m1, labels: ["motor"]}

xpcs.devices.xy_motors.XY_Motors:
- name: damm
  prefix: "8iddSoft:CR8-D1:US"
  x_motor: m2
  y_motor: m3
- name: win_e
  prefix: 8ide:US
  x_motor: m13
  y_motor: m12
- name: win_i
  prefix: 8ide:US
  x_motor: m23
  y_motor: m24

xpcs.devices.fast_shutter.FastShutter:
- name: shutter_8ide
  prefix: "8ideSoft:fastshutter:"

xpcs.devices.filters_8id.Filter2Device:
- name: filter_8ide
  prefix: "8idPyFilter:FL2:"
- name: filter_8idi
  prefix: "8idPyFilter:FL3:"

xpcs.devices.granite.granite_device:
- name: granite
  prefix: "8idiSoft:CR8-I2:US"
  x_motor: m8

xpcs.devices.granite_enable.Valve_Enable:
- name: granite_8idi_valve
  prefix: "8idiSoft:CR8-I2:"

xpcs.devices.hhl_mirrors.HHL_Mirror1:
- name: mr1
  prefix: "8idaSoft:"
xpcs.devices.hhl_mirrors.HHL_Mirror2:
- name: mr2
  prefix: "8idaSoft:"

xpcs.devices.hhl_slits.HHLSlits:
- name: wb_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-1:US"
  pitch_motor: "m3"
  yaw_motor: "m4"
  horizontal_motor: "m1"
  diagonal_motor: "m2"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

- name: mono_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-2:US"
  pitch_motor: "m11"
  yaw_motor: "m12"
  horizontal_motor: "m9"
  diagonal_motor: "m10"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

xpcs.devices.hv_motors.HV_Motors:
- name: bd6a
  prefix: "8iddSoft:CR8-E2:"
  pv_h: m9
  pv_v: m10
- name: bd5a
  prefix: "8iddSoft:CR8-D1:US"
  pv_h: m9
  pv_v: m10

xpcs.devices.idt_mono.IDTMono:
- name: "idt_mono"
  prefix: "8idaSoft:MONO:US"
  bragg_motor: "m1"
  xtal_gap_motor: "m2"
  flag_motor: "m3"
  coarse_pitch_motor: "m5"
  coarse_roll_motor: "m6"
  x_pitch_motor: "m7"
  y_pitch_motor: "m8"

xpcs.devices.labjack_support.LabJack:
- name: "labjack"
  prefix: "8idiSoft:LJT705:"

xpcs.devices.qnw_device.QnwDevice:
- name: qnw_env1
  prefix: "8idiSoft:QNWenv_1:"
  readback_pv: null
- name: qnw_env2
  prefix: "8idiSoft:QNWenv_2:"
  readback_pv: null
- name: qnw_env3
  prefix: "8idiSoft:QNWenv_3:"
  readback_pv: null

xpcs.devices.registers_device.EpicsPvStorageRegisters:
- name: pv_registers
  prefix: "8idiSoft:"

xpcs.devices.slit_base.SlitBase:
- name: sl4_base
  prefix: "8iddSoft:CR8-D1:US"
  h_motor: m15
  v_motor: m16
- name: sl5_base
  prefix: 8ideSoft:CR8-E2:US
  h_motor: m5
  v_motor: m6
- name: sl7_base
  prefix: "8ideSoft:CR8-E2:US"
  h_motor: m15
  v_motor: m16
- name: sl8_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m5
  v_motor: m6
- name: sl9_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m15
  v_motor: m16

xpcs.devices.slit.ID8Optics2Slit2D_HV:
- name: sl4
  prefix: "8iddSoft:Slit1"
- name: sl5
  prefix: "8ideSoft:Slit1"
- name: sl7
  prefix: "8ideSoft:Slit2"
- name: sl8
  prefix: "8idiSoft:Slit1"
- name: sl9
  prefix: "8idiSoft:Slit2"

xpcs.devices.individual_slits.IndividualSlits:
- name: sl9_motors
  prefix: "8idiSoft:CR8-I2:US"
  h_positive_motor: m12
  h_negative_motor: m11
  v_positive_motor: m10
  v_negative_motor: m9

- name: sl5_motors
  prefix: "8ideSoft:CR8-E2:US"
  h_positive_motor: m4
  h_negative_motor: m3
  v_positive_motor: m2
  v_negative_motor: m1

xpcs.devices.softglue.SoftGlue: # This is has to be reviewed
- name: "softglue_8idi"
  prefix: ""
  pv_acq_period: "8idi:SGControl1.A"
  pv_acq_time: "8idi:SGControl1.C"
  pv_num_triggers: "8idi:SGControl1.J"
  pv_start_pulses: "8idi:softGlueA:MUX2-1_IN0_Signal"
  pv_stop_pulses: "8idi:softGlueA:OR-1_IN2_Signal"

xpcs.devices.transfocator.Transfocator:
- name: rl1
  prefix: "8iddSoft:TRANS:"
  pv_y: "m1"
  pv_x: "m2"
  pv_yaw: "m3"
  pv_pitch: "m4"
  pv_lens1: "m5"
  pv_lens2: "m6"
  pv_lens3: "m7"
  pv_lens4: "m8"
  pv_lens5: "m9"
  pv_lens6: "m10"
  pv_lens7: "m11"
  pv_lens8: "m12"
  pv_lens9: "m13"
  pv_lens10: "m14"

- name: rl2
  prefix: "8iddSoft:TRANS:"
  pv_y: "m25"
  pv_x: "m26"
  pv_yaw: "m27"
  pv_pitch: "m28"
  pv_lens1: "m15"
  pv_lens2: "m16"
  pv_lens3: "m17"
  pv_lens4: "m18"
  pv_lens5: "m19"
  pv_lens6: "m20"
  pv_lens7: "m21"
  pv_lens8: "m22"
  pv_lens9: "m23"
  pv_lens10: "m24"

xpcs.devices.func_gen.Function_Generator:
- name: dpKeysight
  prefix: "dpKeysight:KEY1:"

xpcs.devices.huber_diffractometer.Huber_Diffractometer:
- name: huber 
  prefix: "8ideSoft:CR8-E1:"


############################### THESE ARE EXAMPLES OF OTHER DEVICES THAT YOU CAN USE
# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
