"""
Default metadata configuration for APS 8-ID-I beamline.

This module defines the default metadata values used in NeXus files for
experiments at the APS 8-ID-I beamline. These values serve as templates
for various instrument parameters, sample information, and experimental
conditions.
"""

# populated list for the defaults used at 8IDI
default_metadata = {
    "/entry/beamline": "APS-8-ID-E,I",
    "/entry/scan_number": 1,
    "/entry/start_time": "2025-02-10 22:00:00.051404Z",
    "/entry/end_time": "2025-02-10 22:22:22.051404Z",
    "/entry/instrument/detector_1/beam_center_x": 512,
    "/entry/instrument/detector_1/beam_center_y": 512,
    "/entry/instrument/detector_1/beam_center_position_x": 1.0,
    "/entry/instrument/detector_1/beam_center_position_y": 1.0,
    "/entry/instrument/detector_1/position_x": 1.0,
    "/entry/instrument/detector_1/position_y": 1.0,
    "/entry/instrument/detector_1/count_time": 1.0,
    "/entry/instrument/detector_1/detector_name": "Eiger4m",
    "/entry/instrument/detector_1/qmap_file": "eiger4M_qmap_default",
    "/entry/instrument/detector_1/distance": 12.0,
    "/entry/instrument/detector_1/frame_time": 1.0,
    "/entry/instrument/detector_1/x_pixel_size": 7.5e-05,
    "/entry/instrument/detector_1/y_pixel_size": 7.5e-05,
    "/entry/instrument/detector_1/rotation_x": 0.0,
    "/entry/instrument/detector_1/rotation_y": 0.0,
    "/entry/instrument/detector_1/rotation_z": 0.0,
    "/entry/instrument/detector_1/flightpath_swing": 0.0,
    "/entry/instrument/detector_1/compression": "bslz4",
    "/entry/instrument/incident_beam/extent": 1e-06,
    "/entry/instrument/incident_beam/incident_energy": 12.0,
    "/entry/instrument/incident_beam/incident_energy_spread": 0.0001,
    "/entry/instrument/incident_beam/incident_polarization_type": "linear_horizontal",
    "/entry/instrument/incident_beam/incident_beam_intensity": 0.0001,
    "/entry/instrument/incident_beam/transmitted_beam_intensity": 0.0001,
    "/entry/instrument/incident_beam/ring_current": 0.0,
    "/entry/instrument/undulator_1/gap": 1.0,
    "/entry/instrument/undulator_1/energy": 1.0,
    "/entry/instrument/undulator_2/gap": 1.0,
    "/entry/instrument/undulator_2/energy": 1.0,
    "/entry/instrument/monochromator/energy": 1.0,
    "/entry/instrument/monochromator/wavelength": 1.0,
    "/entry/instrument/attenuator_1/attenuator_transmission": 1.0,
    "/entry/instrument/attenuator_1/attenuator_index": 1,
    "/entry/instrument/attenuator_2/attenuator_transmission": 1.0,
    "/entry/instrument/attenuator_2/attenuator_index": 1,
    "/entry/instrument/beam_stop/x_position": 1.0,
    "/entry/instrument/beam_stop/y_position": 1.0,
    "/entry/instrument/beam_stop/size": 4.0,
    "/entry/instrument/datamanagement/workflow_name": "boost_corr workflow",
    # "/entry/instrument/datamanagement/workflow_version": "0.0.1",
    # "/entry/instrument/datamanagement/workflow_kwargs": """{"key": "value"}""",
    "/entry/instrument/bluesky/scan_id": 1,
    "/entry/instrument/bluesky/bluesky_version": "1.0.0",
    "/entry/instrument/bluesky/bluesky_plan": "mesh_scan",
    "/entry/instrument/bluesky/bluesky_plan_kwargs": "mesh_scan_sample_kwargs",
    "/entry/instrument/bluesky/parent_folder": "/path/to/the/parent/folder",
    "/entry/instrument/bluesky/spec_file": "/path/to/this/spec_file_name",
    "/entry/instrument/sl4/vertical_gap": 0.0,
    "/entry/instrument/sl4/vertical_center": 0.0,
    "/entry/instrument/sl4/horizontal_gap": 0.0,
    "/entry/instrument/sl4/horizontal_center": 0.0,
    "/entry/instrument/sl7/vertical_gap": 0.0,
    "/entry/instrument/sl7/vertical_center": 0.0,
    "/entry/instrument/sl7/horizontal_gap": 0.0,
    "/entry/instrument/sl7/horizontal_center": 0.0,
    "/entry/sample/short_description": "Short sample description",
    "/entry/sample/full_description": "Full sample description",
    "/entry/sample/lakeshore1": 1.0,
    "/entry/sample/keithley_chA_SrcLevelV": 1.0,
    "/entry/sample/keithley_chA_SrcLevelI": 1.0,
    "/entry/sample/keithley_chB_SrcLevelV": 1.0,
    "/entry/sample/keithley_chB_SrcLevelI": 1.0,
    "/entry/sample/keithley_chA_MeasRangeV": 1.0,
    "/entry/sample/keithley_chA_MeasRangeI": 1.0,
    "/entry/sample/keithley_chB_MeasRangeV": 1.0,
    "/entry/sample/keithley_chB_MeasRangeI": 1.0,
    "/entry/sample/bk_pid_VAL": 1.0,
    "/entry/sample/bk_pid_RDBK": 1.0,
    "/entry/sample/keysight_func": 1.0,
    "/entry/sample/keysight_freq": 1.0,
    "/entry/sample/keysight_amp": 1.0,      
    "/entry/sample/keysight_phase": 1.0,
    "/entry/sample/keysight_pulse_width": 1.0,
    "/entry/sample/keysight_trigg_source": 1.0,
    "/entry/sample/keysight_trigg_edge": 1.0,
    "/entry/sample/keysight_burst_count": 1.0,
    "/entry/sample/keysight_burst_mode": 1.0,   
    "/entry/sample/keysight_burst_state": 1.0,
    "/entry/sample/keysight_output": 1.0,
    "/entry/user/name": "John Doe",
    "/entry/user/email": "JohnDoe@mail.edu",
    "/entry/user/institution": "Institution Name",
    "/entry/user/cycle": "2025-1",
    "/entry/user/proposal_id": "none",
}
