apstools.devices.area_detector_factory.ad_creator:

# defaults from the factory
#     use_hdf=True,
#     use_image=True,
#     use_overlay=True,
#     use_process=True,
#     use_pva=True,
#     use_roi=True,
#     use_stats=True,
#     use_transform=True,

# flag1ad BasicCam_V34 !proc1 roi1 stats1
# flag2ad BasicCam_V34 !proc1 roi1 stats1
# flag3ad BasicCam_V34 !proc1 roi1 stats1
# flag4ad BasicCam_V34 !image !proc1 roi1 stats1

- name: adsim4M
  prefix: "8idSimDetector4m:"
  # IOC host: beryl
  labels: [ "area_detector", "detectors" ]
  plugins:
  - cam:
      class: id8_common.devices.area_detector.SimDetectorCam_V34
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      write_path_template: /home/8ididata/2023-2/pvaccess_test/
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: adsim16M
  prefix: "8idSimDetector16m:"
  # IOC host: 8idpixirad
  labels: [ "area_detector", "detectors" ]
  plugins:
  - cam:
      class: id8_common.devices.area_detector.SimDetectorCam_V34
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      write_path_template: /home/8ididata/2023-2/pvaccess_test/
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: eiger4M
  prefix: "8idEiger4M:"
  # IOC host: beryl
  # IOC top: /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idEiger4m/iocBoot/ioc8idEiger4m/softioc/8idEiger4m.pl
  labels: [ "area_detector", "detectors" ]
  plugins:
  - badpix1 # apstools 1.7.3+, no extra customization needed
  - cam: { class: id8_common.devices.area_detector.EigerDetectorCam_V34 }
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      # TODO #41 switch to the Voyager-based path structure: "/gdata/..."
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      # same filesystem for IOC & Bluesky
      write_path_template: /home/8ididata/2023-2/pvaccess_test/
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: lambda2M
  prefix: "8idLambda2m:"
  # IOC host: lambda2m
  labels: [ "area_detector", "detectors" ]
  plugins:
  - cam:
      class: id8_common.devices.area_detector.Lambda2MCam
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      write_path_template: "/extdisk/" # TODO: Confirm
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: rigaku3M
  prefix: "8idRigaku3m:"
  # IOC host: rigakusi3m (10.54.116.29)
  labels: [ "area_detector", "detectors" ]
  plugins:
  - cam:
      class: id8_common.devices.area_detector.Rigaku3MCam
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      write_path_template: /home/8ididata/2023-2/pvaccess_test/
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: rigaku500k
  prefix: "8idRigaku:"
  # IOC host: rigaku500k (10.54.116.101)
  labels: [ "area_detector", "detectors" ]
  plugins:
  - cam:
      class: id8_common.devices.area_detector.Rigaku3MCam # assumed
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /home/8ididata/2023-2/pvaccess_test/
      write_path_template: /home/8ididata/2023-2/pvaccess_test/
      kind: normal
  - over1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - proc1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - trans1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }
