apstools.devices.area_detector_factory.ad_creator:

- name: eiger4M
  prefix: "8idEiger4M:"
  # IOC host: beryl
  # IOC top: /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idEiger4m/iocBoot/ioc8idEiger4m/softioc/8idEiger4m.pl
  labels:
  - area_detector
  - detectors
  plugins:
  - badpix1 # apstools 1.7.3+, no extra customization needed
  - cam:
      class: id8_common.devices.area_detector.EigerDetectorCam_V34
  - codec1:
      # needed by PVA and HDF
      class: &CodecPlugin id8_common.devices.area_detector.ID8_CodecPlugin
  - image:
      class: &ImagePlugin id8_common.devices.area_detector.ID8_ImagePlugin
  - hdf1:
      class: &HDF5Plugin id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      # TODO #41 switch to the Voyager-based path structure: "/gdata/..."
      read_path_template: &AD_FILE_PATH /home/8ididata/2023-2/pvaccess_test/
      # same filesystem for IOC & Bluesky
      write_path_template: *AD_FILE_PATH
      kind: normal
  - over1:
      class: &OverPlugin id8_common.devices.area_detector.ID8_OverlayPlugin
  - proc1:
      class: &ProcPlugin id8_common.devices.area_detector.ID8_ProcessPlugin
  - pva:
      class: &PvaPlugin id8_common.devices.area_detector.ID8_PvaPlugin
  - roi1:
      class: &RoiPlugin id8_common.devices.area_detector.ID8_ROIPlugin
  - stats1:
      class: &StatsPlugin id8_common.devices.area_detector.ID8_StatsPlugin
  - trans1:
      class: &TransformPlugin id8_common.devices.area_detector.ID8_TransformPlugin

- name: lambda2M
  prefix: "8idLambda2m:"
  # IOC host: lambda2m
  labels:
  - area_detector
  - detectors
  plugins:
  - cam:
      class: id8_common.devices.area_detector.Lambda2MCam
  - codec1:
      # needed by PVA and HDF
      class: *CodecPlugin
  - image:
      class: *ImagePlugin
  - hdf1:
      class: *HDF5Plugin
      read_path_template: *AD_FILE_PATH
      write_path_template: "/extdisk/" # TODO: Confirm
      kind: normal
  - over1:
      class: *OverPlugin
  - proc1:
      class: *ProcPlugin
  - pva:
      class: *PvaPlugin
  - roi1:
      class: *RoiPlugin
  - stats1:
      class: *StatsPlugin
  - trans1:
      class: *TransformPlugin

- name: rigaku3M
  prefix: "8idRigaku3m:"
  # IOC host: rigakusi3m (10.54.116.29)
  labels:
  - area_detector
  - detectors
  plugins:
  - cam:
      class: id8_common.devices.area_detector.Rigaku3MCam
  - codec1:
      # needed by PVA and HDF
      class: *CodecPlugin
  - image:
      class: *ImagePlugin
  - hdf1:
      class: *HDF5Plugin
      read_path_template: *AD_FILE_PATH
      write_path_template: *AD_FILE_PATH
      kind: normal
  - over1:
      class: *OverPlugin
  - proc1:
      class: *ProcPlugin
  - pva:
      class: *PvaPlugin
  - roi1:
      class: *RoiPlugin
  - stats1:
      class: *StatsPlugin
  - trans1:
      class: *TransformPlugin

- name: rigaku500k
  prefix: "8idRigaku:"
  # IOC host: rigaku500k (10.54.116.101)
  labels:
  - area_detector
  - detectors
  plugins:
  # - badpix1 # apstools 1.7.3+  TODO: Does this IOC have this new plugin?
  - cam:
      class: id8_common.devices.area_detector.Rigaku3MCam # assumed
  - codec1:
      # needed by PVA and HDF
      class: *CodecPlugin
  - image:
      class: *ImagePlugin
  - hdf1:
      class: *HDF5Plugin
      read_path_template: *AD_FILE_PATH
      write_path_template: *AD_FILE_PATH
      kind: normal
  - over1:
      class: *OverPlugin
  - proc1:
      class: *ProcPlugin
  - pva:
      class: *PvaPlugin
  - roi1:
      class: *RoiPlugin
  - stats1:
      class: *StatsPlugin
  - trans1:
      class: *TransformPlugin

# TODO: #116
# flag1
# flag2
# flag3
# flag4
# adsim4M
# adsim16M
