apstools.devices.area_detector_factory.ad_creator:

# - name: adsim4M
#   prefix: "8idSimDetector4m:"
#   # IOC host: beryl
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: adsim16M
#   prefix: "8idSimDetector16m:"
#   # IOC host: beryl
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

- name: eiger4M
  prefix: "8idEiger4m:"
  # IOC host: beryl
  # IOC top: /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idEiger4m/iocBoot/ioc8idEiger4m/softioc/8idEiger4m.pl
  labels: [ "area_detector", "detectors" ]
  plugins:
  - badpix1 # apstools 1.7.3+, no extra customization needed
  - cam: { class: id8_common.devices.area_detector.EigerDetectorCam_V34 }
  - codec1:
      # needed by PVA and HDF
      class: id8_common.devices.area_detector.ID8_CodecPlugin
  - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
  - hdf1:
      class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
      read_path_template: /gdata/dm/8IDI/2025-2/
      # same filesystem for IOC & Bluesky
      write_path_template: /gdata/dm/8IDI/2025-2/
      kind: normal
  - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
  - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
  - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
  - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
  - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
  - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: flag1ad
#   prefix: "8idaSoft:flag1:"
#   # IOC host: s8idioc02
#   # IOC status: /net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idAlviumG1/iocBoot/ioc8idAlviumG1_A1/softioc/8idAlviumG1_A1.pl status
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: flag2ad
#   prefix: "8idaSoft:flag2:"
#   # IOC host: Alvium
#   # IOC status: s8idioc03:/net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idAlviumG1/iocBoot/ioc8idAlviumG1_A1/softioc/8idAlviumG1_A1.pl status
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: flag3ad
#   prefix: "8idaSoft:flag3:"
#   # IOC host: Alvium
#   # IOC status: s8idioc04:/net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idSpinnaker/iocBoot/ioc8idSpinnaker/softioc/8idSpinnaker.pl status
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: flag4ad
#   prefix: "8iddSoft:" # Note: different style name than flag1ad..flag3ad
#   # IOC host: Alvium
#   # IOC status: s8idnx01:/net/s8iddserv/xorApps/epics/synApps_6_3/ioc/8idAlviumG1/iocBoot/ioc8idAlviumG1_D1/softioc/8idAlviumG1_D1.pl status
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.SimDetectorCam_V34
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: lambda2M
#   prefix: "8idLambda2m:"
#   # IOC host: lambda2m
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.Lambda2MCam
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: rigaku3M
#   prefix: "8idRigaku3m:"
#   # IOC host: rigakusi3m (10.54.116.29)
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.Rigaku3MCam
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }

# - name: rigaku500k
#   prefix: "8idRigaku:"
#   # IOC host: rigaku500k (10.54.116.101)
#   labels: [ "area_detector", "detectors" ]
#   plugins:
#   - cam:
#       class: id8_common.devices.area_detector.Rigaku3MCam # assumed
#   - codec1:
#       # needed by PVA and HDF
#       class: id8_common.devices.area_detector.ID8_CodecPlugin
#   - image: { class: id8_common.devices.area_detector.ID8_ImagePlugin }
#   - hdf1:
#       class: id8_common.devices.area_detector.ID8_EpicsFileNameHDF5Plugin
#       read_path_template: /gdata/dm/8IDI/2025-2/
#       write_path_template: /gdata/dm/8IDI/2025-2/
#       kind: normal
#   - overlay1: { class: id8_common.devices.area_detector.ID8_OverlayPlugin }
#   - process1: { class: id8_common.devices.area_detector.ID8_ProcessPlugin }
#   - pva: { class: id8_common.devices.area_detector.ID8_PvaPlugin }
#   - roi1: { class: id8_common.devices.area_detector.ID8_ROIPlugin }
#   - stats1: { class: id8_common.devices.area_detector.ID8_StatsPlugin }
#   - transform1: { class: id8_common.devices.area_detector.ID8_TransformPlugin }
