id8_i.devices.aerotech_stages.AerotechSampleStage:
- name: sample
  prefix: "8idiAerotech:"
  labels: ["sample", "stage"]

id8_i.devices.aerotech_stages.AerotechDetectorStage:
- name: detector
  prefix: "8idiAerotech:"
  labels: ["detector", "stage"]
id8_i.devices.aerotech_stages.AerotechRheometerStage:
- name: rheometer
  prefix: "8idiAerotech:"
  labels: ["rheometer", "stage"]

