id8_common.devices.jj_transfocators.JJtransfocator2x:
- name: crl8id
  prefix: "8idPyCRL:CRL8ID:"
  labels: ["transfocators", "baseline"]
  pitch1_motor: "8iddSoft:TRANS:m4"
  yaw1_motor: "8iddSoft:TRANS:m3"
  x1_motor: "8iddSoft:TRANS:m2"
  y1_motor: "8iddSoft:TRANS:m1"
  pitch2_motor: "8iddSoft:TRANS:m28"
  yaw2_motor: "8iddSoft:TRANS:m27"
  x2_motor: "8iddSoft:TRANS:m26"
  y2_motor: "8iddSoft:TRANS:m25"
