# Guarneri-style device YAML configuration for 8ide

### List of Soft IOCs and their locations ###

# ##s8idioc02:

# flag1.pl
# flag2.pl
# flag3.pl
# flag4.pl
# 8idCryo.pl
# 8idaSoft.pl
# 8iddSoft.pl

# ##s8idioc03:
# 8idKB.pl
# 8idmsPyCRL.pl
# 8ideSoft.pl
# 8idTetra.pl
# 8idiARV1.sh
# 8idIDS.pl
# 8idPyFilter.pl
# XBPM-E.pl


# ##s8idioc04:
# 8ideCRL.pl
# 8idiSoft.pl
# 8idiAerotech.pl
# 8idRobocart.pl
# 8idisamplecam.pl
# XBPM-I.pl


# Beryl:
# 8idEiger4m.pl

id8_common.devices.fofb.FOFB:
  - name: fofb_s09
    prefix: S09-FOFB

apsbits.utils.sim_creator.predefined_device:
  - creator: ophyd.sim.motor
    name: sim_motor
  - creator: ophyd.sim.noisy_det
    name: sim_det

# ophyd.EpicsMotor:
#   - name: fl2
#     prefix: 8ideSoft:CR8-E2:m7
#     labels: ["motor"]
#   - name: fl3
#     prefix: 8idiSoft:CR8-I2:m7
#     labels: ["motor"]
  # - name: flag4
  #   prefix: 8iddSoft:CR8-D1:m1
  #   labels: ["motor"]

id8_common.devices.xy_motors.XY_Motors:
- name: cam_stage_8idi
  prefix: ""
  x_motor: 8ide:m13
  y_motor: 8idiSoft:CR8-I2:m15

id8_common.devices.fast_shutter.FastShutter:
- name: shutter_8ide
  prefix: "8ideSoft:fastshutter:"

id8_common.devices.avs_filters.AVSfilters:
- name: filter_8ide
  prefix: "8idPyFilter:FL2:"

id8_common.devices.granite.granite_device:
- name: granite
  prefix: "8idiSoft:CR8-I2:US"
  x_motor: m8

id8_common.devices.granite_enable.Valve_Enable:
- name: granite_8idi_valve
  prefix: "8idiSoft:CR8-I2:"

id8_common.devices.hhl_mirrors.HHL_Mirror1:
- name: mr1
  prefix: "8idaSoft:"
id8_common.devices.hhl_mirrors.HHL_Mirror2:
- name: mr2
  prefix: "8idaSoft:"

id8_common.devices.hhl_slits.HHLSlits:
- name: wb_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-1:US"
  pitch_motor: "m3"
  yaw_motor: "m4"
  horizontal_motor: "m1"
  diagonal_motor: "m2"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

- name: mono_slit
  prefix: "8idaSoft:CR8-A1:US"
  secondary_prefix: "8idaSoft:SL-2:US"
  pitch_motor: "m11"
  yaw_motor: "m12"
  horizontal_motor: "m9"
  diagonal_motor: "m10"
  hgap_motor: "hSize"
  hcen_motor: "hCenter"
  vgap_motor: "vSize"
  vcen_motor: "vCenter"

id8_common.devices.hv_motors.HV_Motors:
- name: bd6a
  prefix: "8ideSoft:CR8-E2:"
  pv_h: m9
  pv_v: m10
- name: bd5a
  prefix: "8iddSoft:CR8-D1:"
  pv_h: m9
  pv_v: m10

id8_common.devices.labjack_support.LabJack:
- name: "labjack"
  prefix: "8idiSoft:LJT705:"

id8_common.devices.qnw_device.QnwDevice:
- name: qnw_env1
  prefix: "8idiSoft:QNWenv_1:"
  readback_pv: null
- name: qnw_env2
  prefix: "8idiSoft:QNWenv_2:"
  readback_pv: null
- name: qnw_env3
  prefix: "8idiSoft:QNWenv_3:"
  readback_pv: null

# id8_common.devices.qnw_vac_device.QnwDevice:
# - name: qnw_vac1
#   prefix: "8idiSoft:QNWvac_1:"
#   readback_pv: null
# - name: qnw_vac2
#   prefix: "8idiSoft:QNWvac_2:"
#   readback_pv: null
# - name: qnw_vac3
#   prefix: "8idiSoft:QNWvac_3:"
#   readback_pv: null

id8_common.devices.registers_device.EpicsPvStorageRegisters:
- name: pv_registers
  prefix: "8ideSoft:" # could be "8idiSoft" too

id8_common.devices.slit_base.SlitBase:
- name: sl4_base
  prefix: "8iddSoft:CR8-D1:US"
  h_motor: m15
  v_motor: m16
- name: sl5_base
  prefix: 8ideSoft:CR8-E2:US
  h_motor: m5
  v_motor: m6
- name: sl7_base
  prefix: "8ideSoft:CR8-E2:US"
  h_motor: m15
  v_motor: m16
- name: sl8_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m5
  v_motor: m6
- name: sl9_base
  prefix: "8idiSoft:CR8-I2:US"
  h_motor: m15
  v_motor: m16

id8_common.devices.slit.ID8Optics2Slit2D_HV:
- name: sl4
  prefix: "8iddSoft:Slit1"
- name: sl5
  prefix: "8ideSoft:Slit1"
- name: sl7
  prefix: "8ideSoft:Slit2"
- name: sl8
  prefix: "8idiSoft:Slit1"
- name: sl9
  prefix: "8idiSoft:Slit2"

id8_common.devices.individual_slits.IndividualSlits:
- name: sl9_motors
  prefix: "8idiSoft:CR8-I2:US"
  h_positive_motor: m12
  h_negative_motor: m11
  v_positive_motor: m10
  v_negative_motor: m9

- name: sl5_motors
  prefix: "8ideSoft:CR8-E2:US"
  h_positive_motor: m4
  h_negative_motor: m3
  v_positive_motor: m2
  v_negative_motor: m1

id8_common.devices.softglue.SoftGlue: 
- name: "softglue"
  prefix: ""
  pv_acq_period: "8idMZ1:userTran1.A"
  pv_acq_time: "8idMZ1:userTran1.C"
  pv_num_triggers: "8idMZ1:userTran1.J"
  pv_start_pulses: "8idMZ1:SG:plsTrn-1_Inp_Signal"  # 1! for starting pulses
  pv_stop_pulses: "8idMZ1:SG:plsTrn-1_Dis_Signal"  # 1 for stopping pulses. Change back to 0 when done.
  pv_enable_rigaku: "8idMZ1:SG:MUX2-1_SEL_Signal" # '1' for switching to Rigaku, '0' for all other detectors
  pv_clear1: "8idMZ1:SG:UpCntr-1_CLEAR_Signal"  # example PV for clearing a counter or similar action
  pv_clear2: "8idMZ1:SG:UpCntr-2_CLEAR_Signal"  # example PV for clearing a counter or similar action
  pv_clear3: "8idMZ1:SG:UpCntr-3_CLEAR_Signal"  # example PV for clearing a counter or similar action

id8_common.devices.softglue.softglue_mz2:  
- name: "softglue_8id_mz2"
  prefix: ""

id8_common.devices.softglue.softglue_acq8id:  
- name: "softglue_8id_acq"
  prefix: ""

id8_common.devices.transfocator.Transfocator:
- name: rl1
  prefix: "8iddSoft:TRANS:"
  pv_y: "m1"
  pv_x: "m2"
  pv_yaw: "m3"
  pv_pitch: "m4"
  pv_lens1: "m5"
  pv_lens2: "m6"
  pv_lens3: "m7"
  pv_lens4: "m8"
  pv_lens5: "m9"
  pv_lens6: "m10"
  pv_lens7: "m11"
  pv_lens8: "m12"
  pv_lens9: "m13"
  pv_lens10: "m14"

- name: rl2
  prefix: "8iddSoft:TRANS:"
  pv_y: "m25"
  pv_x: "m26"
  pv_yaw: "m27"
  pv_pitch: "m28"
  pv_lens1: "m15"
  pv_lens2: "m16"
  pv_lens3: "m17"
  pv_lens4: "m18"
  pv_lens5: "m19"
  pv_lens6: "m20"
  pv_lens7: "m21"
  pv_lens8: "m22"
  pv_lens9: "m23"
  pv_lens10: "m24"

id8_common.devices.huber_diffractometer.Huber_Diffractometer:
- name: huber
  prefix: "8ideSoft:CR8-E1:"

id8_common.devices.lakeshore.Lakeshore:
- name: lakeshore1
  prefix: "8ideSoft:LS336:1:"
- name: lakeshore2
  prefix: "8ideSoft:LS336:2:"

# id8_common.devices.rheometer_wait_signal.Rheometer_Wait:
# - name: mcr_wait_signal
#   prefix: "8idMZ4:SG:"

id8_common.devices.flight_path.FlightPath:
- name: flight_path_8idi
  prefix: "8idiSoft:FLIGHT:"

id8_common.devices.ur5_control.UR5:
- name: ur5
  prefix: "RobocartUR5:"


id8_common.devices.tetramm_picoammeter.MyTetrAMM:
- name: tetramm1
  prefix: "8idTetra:QUAD1:"
  port_name: "QUAD1"
- name: tetramm2
  prefix: "8idTetra:QUAD2:"
  port_name: "QUAD2"
- name: tetramm3
  prefix: "8idTetra:QUAD3:"
  port_name: "QUAD3"
- name: tetramm4
  prefix: "8idTetra:QUAD4:"
  port_name: "QUAD4"

# id8_common.devices.sydor_tp4u.SydorTP4U:
# - name: xbpm1
#   prefix: "8ideBPM:T4U_BPM:"

# id8_common.devices.func_gen.Function_Generator:
# - name: dpKeysight
#   prefix: "dpKeysight:KEY1:"
# - name: keysight
#   prefix: "8idKeysight:KEY1:"

id8_common.devices.idt_mono.BraggGap_Monochromator:
- name: mono
  prefix: "8idaSoft:MN1:"
  bragg_motor: "Bragg"
  gap_motor: "Gap"

# id8_common.devices.undulator.Undulator:
# - name: undulator
#   prefix: "S08ID:"

id8_common.devices.aerotech_stages.AerotechSampleStage:
- name: sample
  prefix: "8idiAerotech:"
  labels: ["sample", "stage"]

id8_common.devices.aerotech_stages.AerotechDetectorStage:
- name: detector
  prefix: "8idiAerotech:"
  labels: ["detector", "stage"]

id8_common.devices.aerotech_stages.AerotechRheometerStage:
- name: rheometer
  prefix: "8idiAerotech:"
  labels: ["rheometer", "stage"]

id8_common.devices.flight_tube.FlightTubeDetector:
- name: "det_motors"
  prefix: "8idiSoft:FLIGHT:"

id8_common.devices.flight_tube.FlightTubeBeamStop:
- name: "bs_motors"
  prefix: "8idiSoft:FLIGHT:"

id8_common.devices.undulator.RevolverUndulator_8ID:
- name: undulator_upstream
  prefix: "S08ID:USID:"
- name: undulator_downstream
  prefix: "S08ID:DSID:"

hklpy2.creator:
- name: sim_psic
  geometry: E6C
  solver: hkl_soleil
  reals: [ "mu", "eta", "chi", "phi", "nu", "delta" ]  # psic names
  labels: [ "diffractometer" ]
- name: psic
  geometry: E6C
  solver: hkl_soleil
  prefix: "8ideSoft:CR8-E1:"  
  labels: [ "diffractometer" ]
  reals:
    mu: m6
    eta: m7
    chi: m8
    phi: m9
    nu: m4
    delta: m5

id8_common.devices.pin_diode.PIND:
- name: pd
  prefix: "8ideSoft:pdu1:"

# id8_common.devices.keithley.Keithley:
# - name: keithley_chA
#   prefix: "8idKeithley2600:SMU:A:"
# - name: keithley_chB
#   prefix: "8idKeithley2600:SMU:B:"

# id8_common.devices.bk_powersupply.bk_pid:
# - name: bk_pid
#   prefix: "8idiSoft:BPMpid."
  
# id8_common.devices.meascomp_usb_ctr.MeasCompCTR:
#   - name: daq1
#     prefix: "8idDAQ1:"

# id8_common.devices.meascomp_usb_ctr.MeasCompCtrMcs:
#   - name: mcs
#     prefix: "8idDAQ1:"

# id8_common.devices.jj_transfocators.JJtransfocator2x:
# - name: crl8id
#   prefix: ""
#   labels: ["transfocators", "baseline"]
#   pitch1_motor: "8iddSoft:TRANS:m4"
#   yaw1_motor: "8iddSoft:TRANS:m3"
#   x1_motor: "8iddSoft:TRANS:m2"
#   y1_motor: "8iddSoft:TRANS:m1"
#   pitch2_motor: "8iddSoft:TRANS:m28"
#   yaw2_motor: "8iddSoft:TRANS:m27"
#   x2_motor: "8iddSoft:TRANS:m26"
#   y2_motor: "8iddSoft:TRANS:m25"

############################### THESE ARE EXAMPLES OF OTHER DEVICES THAT YOU CAN USE
# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

# ophyd.scaler.ScalerCH:
# - name: scaler1
#   prefix: vme:scaler1
#   labels: ["scalers", "detectors"]

# ophyd.EpicsMotor:
# - {name: m1, prefix: gp:m1, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1



