# configuration.yml

# configuration for the instrument package
# simple key:value pairs

CONTROLS_SUBNET: 116

DATABROKER_CATALOG: &databroker_catalog 8idi_xpcs

# default RunEngine metadata
RUNENGINE_METADATA:
  beamline_id: 8idi_XPCS
  instrument_name: 8-ID-I XPCS
  proposal_id: XPCS Development
  databroker_catalog: *databroker_catalog

# Uncomment and edit to define a PV to use for the `scan_id`.
# The default behavior is to use `RE.md["scan_id"]`.
# RUN_ENGINE_SCAN_ID_PV: "IOC:integer"
# 8idDAQ1:Reg0


# permissions
ALLOW_AREA_DETECTOR_WARMUP: true
ENABLE_AREA_DETECTOR_IMAGE_PLUGIN: true
ENABLE_CALCS: false
USE_PROGRESS_BAR: false
WRITE_NEXUS_DATA_FILES: false
NEXUS_WARN_MISSING_CONTENT: false
NEXUS_FILE_EXTENSION: hdf
WRITE_SPEC_DATA_FILES: false

# APS Data Management
DM_SETUP_FILE: "/home/dm/etc/dm.setup.sh"


AREA_DETECTOR:
  LAMBDA_2M:
    PV_PREFIX: "8idLambda2m:"
    NAME: lambda2M
  SIMDET_4M:
    # For reference:
    # /net/s8iddserv/xorApps/epics/synApps_6_2_1/ioc/8idSimDetectors/iocBoot/ioc8idSimDetector4m/softioc/8idSimDetector4m.pl start
    PV_PREFIX: "8idSimDetector4m:"
    NAME: simdet4M
  SIMDET_16M:
    PV_PREFIX: "8idSimDetector16m:"
    NAME: simdet16M

# ----------------------------------

# Directory to "autosave" the RE.md dictionary (uses PersistentDict)
# Uncomment and modify to change from the default.
# RUNENGINE_MD_PATH: /home/USERNAME/Bluesky_RunEngine_md

# override default control layer for ophyd
# if undefined, defaults to PyEpics
# OPHYD_CONTROL_LAYER: PyEpics
# OPHYD_CONTROL_LAYER: caproto

# Uncomment any of these to override the defaults
LOGGING:
  # MAX_BYTES: 1000000
  NUMBER_OF_PREVIOUS_BACKUPS: 9
  # LOG_PATH: /tmp
  # If LOG_PATH undefined, this session will log into PWD/logs/
  # where PWD is present working directory when session is started

# default timeouts (seconds)
PV_READ_TIMEOUT: &TIMEOUT 30
PV_WRITE_TIMEOUT: *TIMEOUT
PV_CONNECTION_TIMEOUT: 10

XMODE_DEBUG_LEVEL: Minimal

# Minimum software package version checks: MAJOR.minor (no .patch).
# These will be converted to tuple() for comparisons.
MINIMUM_PYTHON_VERSION:
  - 3
  - 10
MINIMUM_BLUESKY_VERSION:
  - 1
  - 10
MINIMUM_DATABROKER_VERSION:
  - 1
  - 2
MINIMUM_OPHYD_VERSION:
  - 1
  - 7

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 1.0.1
