name: Pre-Commit Checks

on:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Run Pre-Commit Checks
      uses: pre-commit/action@v3.0.1
